spring.application.name=spring-cloud-config-server
server.port=8888
#spring.cloud.config.server.git.uri=file:///Users/rangakaranam/Ranga/git/01.udemy-course-repos/spring-microservices-v2/03.microservices/git-localconfig-repo
#file:///C:/Users/home/Desktop/yourProject/git-repo
spring.cloud.config.server.git.uri=file:///E:/KHOA/HAPPY_CODING/Microservices/spring-microservices-v3-main/spring-microservices-v3-main/gitconfig-localrepo
spring.cloud.config.server.git.default-label=master

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=false
logging.level.org.springframework.cloud.config.server.environment=DEBUG